In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("excel_data_cleaning_project_dataset.xlsx")

In [ ]:
df.head()

,OrderID,CustomerName,Email,City,Product,Quantity,UnitPrice,TotalAmount,PaymentMethod,OrderDate
0,ORD1037,Sarah Johnson,sarah.johnson@example.com,HOUSTON,Monitor,1,199,199,Credit Card,18/05/2023
1,ORD1003,Emily Davis,EMILY.DAVIS@EXAMPLE.COM,HOUSTON,Tablet,1,299,299,Bank Transfer,2023-01-24 00:00:00
2,ORD1003,jane smith,jane.smith@example.com,philadelphia,Monitor,5,199,995,credit card,2023-05-28 00:00:00
3,ORD1019,John Doe,john.doe@example.com,los angeles,Smartphone,4,299,1196,Bank Transfer,19/05/2023
4,ORD1004,Michael Brown,MICHAEL.BROWN@EXAMPLE.COM,Phoenix,Monitor,2,499,998,Bank Transfer,2023-01-25 00:00:00

In [ ]:
#Find missing values
df.isna().sum()

OrderID          0
CustomerName     0
Email            0
City             0
Product          0
Quantity         0
UnitPrice        0
TotalAmount      0
PaymentMethod    0
OrderDate        0
dtype: int64

In [ ]:
df.shape[0]

120

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df[~df['CustomerName'].str.istitle()]['CustomerName'] #Check for proper names that aren't capitalised

2      jane smith
38     jane smith
41     jane smith
59     jane smith
65     jane smith
66     jane smith
70     jane smith
79     jane smith
82     jane smith
88     jane smith
89     jane smith
93     jane smith
94     jane smith
100    jane smith
103    jane smith
108    jane smith
117    jane smith
Name: CustomerName, dtype: object

In [ ]:
df['CustomerName'] = df['CustomerName'].str.title() #Capitalise customer names

In [ ]:
df[df['Email'].str.isupper()]['Email'] #Check for emails not properly formatted

1        EMILY.DAVIS@EXAMPLE.COM
4      MICHAEL.BROWN@EXAMPLE.COM
8          DAVID.LEE@EXAMPLE.COM
9           ANNA.KIM@EXAMPLE.COM
11          ANNA.KIM@EXAMPLE.COM
16          JOHN.DOE@EXAMPLE.COM
19     MICHAEL.BROWN@EXAMPLE.COM
20     SARAH.JOHNSON@EXAMPLE.COM
24       EMILY.DAVIS@EXAMPLE.COM
27     MICHAEL.BROWN@EXAMPLE.COM
28     SARAH.JOHNSON@EXAMPLE.COM
32     MICHAEL.BROWN@EXAMPLE.COM
41        JANE.SMITH@EXAMPLE.COM
42         DAVID.LEE@EXAMPLE.COM
47          JOHN.DOE@EXAMPLE.COM
50     MICHAEL.BROWN@EXAMPLE.COM
51          ANNA.KIM@EXAMPLE.COM
52       EMILY.DAVIS@EXAMPLE.COM
56     MICHAEL.BROWN@EXAMPLE.COM
57       EMILY.DAVIS@EXAMPLE.COM
61       EMILY.DAVIS@EXAMPLE.COM
64          ANNA.KIM@EXAMPLE.COM
65        JANE.SMITH@EXAMPLE.COM
70        JANE.SMITH@EXAMPLE.COM
86          JOHN.DOE@EXAMPLE.COM
92          ANNA.KIM@EXAMPLE.COM
94        JANE.SMITH@EXAMPLE.COM
96      CHRIS.WILSON@EXAMPLE.COM
99          ANNA.KIM@EXAMPLE.COM
101    SARAH.JOHNSON@EXAMPLE.COM
110     CHRIS.WILSON@EXAMPLE.COM
119      EMILY.DAVIS@EXAMPLE.COM
Name: Email, dtype: object

In [ ]:
df['Email'] = df['Email'].str.lower()

In [ ]:
df[~df['Product'].str.istitle()]['Product']

11     laptop
14     laptop
21     laptop
22     laptop
24     laptop
28     laptop
29     laptop
30     laptop
38     laptop
49     laptop
52     laptop
53     laptop
57     laptop
58     laptop
81     laptop
90     laptop
94     laptop
100    laptop
102    laptop
104    laptop
113    laptop
114    laptop
115    laptop
Name: Product, dtype: object

In [ ]:
df['Product'] = df['Product'].str.title()

In [ ]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'], dayfirst=True, errors='coerce')

In [ ]:
df['OrderDate'] = df['OrderDate'].dt.strftime('%Y-%m-%d')

In [ ]:
df[~df['Quantity'] * df['UnitPrice'] == df['TotalAmount']]['TotalAmount'] #Correctly formatted

Series([], Name: TotalAmount, dtype: int64)

In [ ]:
df.to_excel("cleaned_data.xlsx", index=False)